estoque/urls.py
# flake8: noqa
from django.urls import path
from . import views

app_name = 'estoque'

urlpatterns = [
    path('', views.ListaEstoque.as_view(),name="lista"),
    path('create/', views.create, name='create'),
    path('detail/<int:estoque_id>/', views.detail, name='detail'),
    path('update/<int:estoque_id>/', views.update, name='update'),
    path('delete/<int:estoque_id>/', views.delete, name='delete'),
    path('search/', views.search, name='search'),

]

project/urls.py
# flake8: noqa
"""
URL configuration for project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('estoque.urls')),
    path('funcionario/', include('funcionario.urls')),
    path('requisicao/', include('requisicao.urls')),
    path('saida/', include('saida.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saida/urls.py
# flake8: noqa
from django.urls import path
from . import views

app_name = 'saida'

urlpatterns = [
    path('', views.ListaSaida.as_view(), name='lista'),
    path('create/', views.create, name='create'),
]

estoque/models.py
# flake8: noqa
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from pathlib import Path
from django.conf import settings

# Create your models here.
class Estoque(models.Model):
    nome = models.CharField(max_length=255, verbose_name='Nome do Equipamento')
    tipo = models.CharField(
        max_length=25,
        default='Roteador',
        choices= (
            ('Roteador','Roteador'),
            ('ONU','ONU'),
            ('Conector','Conector'),
            ('Cabo','Cabos'),
            ('Outros','Outros'),
        )
    )
    quantidade = models.PositiveBigIntegerField(default=1)
    imagem = models.ImageField(upload_to='equipamento_imagens', blank=True, null= True)
    mac = models.CharField(max_length=17, verbose_name='Mac do Equipamento',blank=True, null=True)
    cadastrado = models.DateTimeField(auto_now_add=True)
    # user.post_created_by.all
    cadastrado_por = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='Cadastrado por: ',
        related_name='estoque_cadastro_por'
    )
    atualizado = models.DateTimeField(auto_now=True)
    # user.post_updated_by.all
    atualizado_por = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name ='Atualizado por: ',
        related_name='estoque_atualizado_por'
    )

    def __str__(self):
        return self.nome
    
    @staticmethod
    def resize_image(img, new_width=200):
        img_full_path = Path(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size
                   
        if original_width <= new_width:               
            img_pil.close()
            return

        new_height = 200

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
            )

    def save (self, *args, **kwargs):
        super().save(*args, **kwargs)
        max_image_size = 200

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)
           
    
    class Meta:
          verbose_name = 'Estoque'
          verbose_name_plural = 'Estoque'

estoque/views.py
# flake8: noqa
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views import View
from django.http import HttpResponse
from . import models
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django import forms
from estoque.models import Estoque
from django.db.models import Q
# Create your views here.

class ListaEstoque(ListView):
    model = models.Estoque
    template_name = 'estoque/lista.html'
    context_object_name = 'estoques'


def create(request):
    form_action = reverse('estoque:create')

    if request.method == 'POST':
        form = estoqueForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            estoque = form.save()
            estoque.save()

            return redirect('estoque:lista')

        return render(
            request,
            'estoque/create.html',
            context
        )

    context = {
        'form': estoqueForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'estoque/create.html',
        context
    )

def detail(request, estoque_id):
   
    # single_Estoque = Estoque.objects.filter(pk=estoque_id).first()
    single_estoque = get_object_or_404(
        Estoque, pk=estoque_id,
    )
    
    context = {
        'estoque': single_estoque,
    
    }

    return render(
        request,
        'estoque/detail.html',
        context
    )

def update(request, estoque_id):
    estoque = get_object_or_404(
        Estoque, pk=estoque_id,
    )
    form_action = reverse('estoque:update', args=(estoque_id,))

    if request.method == 'POST':
        form = estoqueForm(request.POST, request.FILES, instance=estoque)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            estoque = form.save()
            estoque.save()

            return redirect('estoque:detail', estoque_id=estoque.pk)

        return render(
            request,
            'estoque/update.html',
            context
        )

    context = {
        'form': estoqueForm(instance=estoque),
        'form_action': form_action,
    }

    return render(
        request,
        'estoque/update.html',
        context
    )

    
def delete(request, estoque_id):
    estoque = get_object_or_404(
        Estoque, pk=estoque_id,
    )

    if request.method == 'POST':
        estoque.delete()
        return redirect('estoque:lista')

    return render(
        request,
        'estoque/delete.html',
                {
            'estoque': estoque,
            
        }
    )

class estoqueForm(forms.ModelForm):
    imagem = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        ),
        required=False
    )
    nome = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Informe o nome do equipamento',
            }
        ),
        label='Equipamento',
    )



    class Meta:
        model = models.Estoque
        fields = (
            'nome', 'tipo', 'quantidade',
            'imagem', 
        )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('estoque:lista')

    estoques = Estoque.objects \
        .filter(
            Q(nome__icontains=search_value)  
            )

    context = {
        'estoques' : estoques,
       
    }

    return render(
        request,
        'estoque/lista.html',
        context
    )

estoque/templates/estoque/create.html
{% extends 'global/base.html' %}

{% block conteudo %}

  <div class="form-wrapper">

    <h2>Cadastrar Equipamento</h2>

    <form 
      action=""
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}

    
      {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
            {{ field }}
          </div>
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Cadastrar</button>
        </div>
      </div>

    </form>
  </div>
{% endblock conteudo %}

estoque/templates/estoque/delete.html
{% extends 'global/base.html' %}

{% block conteudo %}
<form 
action=""
method="POST"
enctype="multipart/form-data"
>
{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="form-wrapper">
                <h1 >
                {{ estoque.nome}} 
                </h1>

                <p><b>Quantidade</b> {{ estoque.quantidade }}</p>
                <p><b>Tipo:</b> {{ estoque.tipo }}</p>
                <p><b>Cadastrado :</b> {{ estoque.cadastrado }}</p>
                <p><b>Cadastrado por:</b> {{ estoque.cadastrado_por }}</p>
                <p><b>Atualizado:</b> {{ estoque.atualizado }}</p>
                <p><b>Atualizado por:</b> {{ estoque.atualizado_por }}</p>
            </div>
        </div>
        <div class="col">
            <div class="form-wrapper">
                {% if estoque.imagem %}
                <p>
                <img src='{{ estoque.imagem.url }}'>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="form-content">
        <div class="form-group">
          <button class="btn btn-danger" type="submit">Deletar Equipamento</button>
        </div>
      </div>
      <div class="form-content">
        <div class="form-group">
            <a class="btn btn-primary " href="{% url 'estoque:lista' %}">Voltar para lista de Equipamentos</a>
        </div>
      </div>

</div>    
</form>
{% endblock conteudo %}

estoque/templates/estoque/detail.html
{% extends 'global/base.html' %}

{% block conteudo %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="form-wrapper">
                <h1 >
                {{ estoque.nome}} 
                </h1>

                <p><b>Quantidade</b> {{ estoque.quantidade }}</p>
                <p><b>Tipo:</b> {{ estoque.tipo }}</p>
                <p><b>Cadastrado :</b> {{ estoque.cadastrado }}</p>
                <p><b>Cadastrado por:</b> {{ estoque.cadastrado_por }}</p>
                <p><b>Atualizado:</b> {{ estoque.atualizado }}</p>
                <p><b>Atualizado por:</b> {{ estoque.atualizado_por }}</p>
            </div>
        </div>
        <div class="col">
            <div class="form-wrapper">
                {% if estoque.imagem %}
                <p>
                <img src='{{ estoque.imagem.url }}'>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
    <a class="btn btn-primary btn-lg btn-block" href="{% url 'estoque:lista' %}">Voltar</a>
</div>    
{% endblock conteudo %}

estoque/templates/estoque/lista.html
{% extends "global/base.html" %}

{% block conteudo %}

<div class="table-responsive">
    <form action="{% url 'estoque:search' %}" method="GET">
        <input
        type="search"
        class="form-control mr-sm-2"
        placeholder="Procurar na lista"
        id="search"
        name="q"
        >
    </form>


    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Equipamento</th>
            <th>Quantidade</th>
            <th>Atualizado</th>
            <th>Ações</th>

        </tr>

        {% for estoque in  estoques %}
        <tr>
            <td class="d-none d-lg-block">
                {% if estoque.imagem %}
                    <img class="cart-img" src="{{ estoque.imagem.url }}">
                {% endif %}
            </td>
            <td>{{ estoque.nome }}</td>
            <td>{{ estoque.quantidade }}</td>
            <td> {{estoque.atualizado | date:'d/m/Y \à\s H:i'}}  </td>
            <td>
                <a  class="btn btn-success"data-toggle="tooltip"  title="Detalhes" href="{% url 'estoque:detail' estoque.id %}"><i class="far fa-eye"></i></a>
                <a  class="btn btn-warning"data-toggle="tooltip" title="Editar" href="{% url 'estoque:update' estoque.id %}"><i class="fas fa-edit"></i></a>
                <a  class="btn btn-danger"data-toggle="tooltip"  title="Excluir" href="{% url 'estoque:delete' estoque.id %}"><i class="far fa-trash-alt"></i></a>

              </td>
        </tr>
        {% endfor %}


    </table>
</div>

{% endblock %}

estoque/templates/estoque/update.html
{% extends 'global/base.html' %}

{% block conteudo %}

  <div class="form-wrapper">

    <h2>Editar Cadastro de Equipamento</h2>

    <form 
      action=""
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}

    
      {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
            {{ field }}
          </div>
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Atualizar Dados</button>
        </div>
      </div>

    </form>
  </div>
{% endblock conteudo %}