funcionario/urls.py
# flake8: noqa
from django.urls import path
from . import views

app_name = 'funcionario'

urlpatterns = [
    path('', views.ListaFuncionario.as_view(), name='lista'),
    path('create/', views.create, name='create'),
    path('update/<int:funcionario_id>/', views.update, name='update'),
    path('delete/<int:funcionario_id>/', views.delete, name='delete'),
]

project/urls.py
# flake8: noqa
"""
URL configuration for project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('estoque.urls')),
    path('funcionario/', include('funcionario.urls')),
    path('requisicao/', include('requisicao.urls')),
    path('saida/', include('saida.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saida/urls.py
# flake8: noqa
from django.urls import path
from . import views

app_name = 'saida'

urlpatterns = [
    path('', views.ListaSaida.as_view(), name='lista'),
    path('create/', views.create, name='create'),
]

funcionario/models.py
# flake8: noqa
from django.db import models

class Funcionario(models.Model):
    nome = models.CharField(max_length=255, verbose_name='Nome do Funcinário')
    cidade = models.CharField(max_length=255, verbose_name='Cidade')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'

funcionario/views.py
# flake8: noqa

from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views import View
from django.http import HttpResponse
from . import models
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django import forms
from funcionario.models import Funcionario
from . import models

class ListaFuncionario(ListView):
    model = models.Funcionario
    template_name = 'funcionario/lista.html'
    context_object_name = 'funcionarios'



def create(request):
    form_action = reverse('funcionario:create')

    if request.method == 'POST':
        form = funcionarioForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            funcionario = form.save()
            funcionario.save()

            return redirect('funcionario:lista')

        return render(
            request,
            'funcionario/create.html',
            context
        )

    context = {
        'form': funcionarioForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'funcionario/create.html',
        context
    )
class funcionarioForm(forms.ModelForm):

    nome = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Informe o nome do Funcionário',
            }
        ),
        label='Nome',
    )
    
    cidade = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Informe a Cidade do Funcionário',
            }
        ),
        label='Cidade',
    )

    class Meta:
        model = models.Funcionario
        fields = (
            'nome', 'cidade', 
        )


def update(request, funcionario_id):
    funcionario = get_object_or_404(
        Funcionario, pk=funcionario_id,
    )
    form_action = reverse('funcionario:update', args=(funcionario_id,))

    if request.method == 'POST':
        form = funcionarioForm(request.POST, request.FILES, instance=funcionario)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            funcionario = form.save()
            funcionario.save()

            return redirect('funcionario:lista')

        return render(
            request,
            'funcionario/update.html',
            context
        )

    context = {
        'form': funcionarioForm(instance=funcionario),
        'form_action': form_action,
    }

    return render(
        request,
        'funcionario/update.html',
        context
    )

    
def delete(request, funcionario_id):
    funcionario = get_object_or_404(
        Funcionario, pk=funcionario_id,
    )

    if request.method == 'POST':
        funcionario.delete()
        return redirect('funcionario:lista')

    return render(
        request,
        'funcionario/delete.html',
                {
            'funcionario': funcionario,
            
        }
    )

funcionario/templates/funcionario/create.html
{% extends 'global/base.html' %}

{% block conteudo %}

  <div class="form-wrapper">

    <h2>Cadastrar Funcionário</h2>

    <form 
      action=""
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}

    
      {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
            {{ field }}
          </div>
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Cadastrar</button>
        </div>
      </div>

    </form>
  </div>
{% endblock conteudo %}

funcionario/templates/funcionario/delete.html
{% extends 'global/base.html' %}

{% block conteudo %}
<form 
action=""
method="POST"
enctype="multipart/form-data"
>
{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="form-wrapper">
                <h1 >
                {{ funcionario.nome}} 
                </h1>

                <p><b>Cidade: </b> {{ funcionario.cidade }}</p>

            </div>
        </div>
    </div>
    <div class="form-content">
        <div class="form-group">
          <button class="btn btn-danger" type="submit">Deletar Funcionário</button>
        </div>
      </div>
      <div class="form-content">
        <div class="form-group">
            <a class="btn btn-primary " href="{% url 'funcionario:lista' %}">Voltar para lista de Funcionários</a>
        </div>
      </div>

</div>    
</form>
{% endblock conteudo %}

funcionario/templates/funcionario/lista.html
{% extends "global/base.html" %}

{% block conteudo %}

<div class="table-responsive">
    <h1>Lista de Funcionários</h1>
    <table class="table">
        <tr>
            <th>Nome</th>
            <th>Cidade</th>
            <th>Ações</th>

        </tr>

        {% for funcionario in  funcionarios %}
        <tr>
            <td>{{ funcionario.nome }}</td>
            <td>{{ funcionario.cidade }}</td>
            <td>
                <a  class="btn btn-warning"data-toggle="tooltip" title="Editar" href="{% url 'funcionario:update' funcionario.id %}"><i class="fas fa-edit"></i></a>
                <a  class="btn btn-danger"data-toggle="tooltip"  title="Excluir" href="{% url 'funcionario:delete' funcionario.id %}"><i class="far fa-trash-alt"></i></a>

              </td>
        </tr>
        {% endfor %}


    </table>
</div>

{% endblock %}

funcionario/templates/funcionario/update.html
{% extends 'global/base.html' %}

{% block conteudo %}

  <div class="form-wrapper">

    <h2>Editar Cadastro de Funcionário</h2>

    <form 
      action=""
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}

    
      {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
            {{ field }}
          </div>
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Atualizar Dados</button>
        </div>
      </div>

    </form>
  </div>
{% endblock conteudo %}